### ISSUE TITLE
str has no attribute decode

### ISSUE THREAD

**Issue by GitauHarrison** [miguelgrinberg/microblog-authy#3]
@miguelgrinberg 
Following your update to enable push notifications using Twilio Authy, I get the error 
```
AttributeError: 'str' object has no attribute 'decode'
```

The logs point out to `get_registration_jwt()` function when it is called by `enable_2fa`. To be more specific, this line:

```
def get_authy_registration_jwt(user_id, expires_in=5 * 60):
    # ...
    return jwt.encode(payload,
                      current_app.config['AUTHY_PRODUCTION_API_KEY']).decode()
```
I am able to get it to work by removing `decode()` though I am not certain if that is the best way to go about it. Digging this issue up, one recommendation was to revert to pre -  PyJWT v2.0.0 (`PyJWT==1.7.1`) release as seen [here](https://stackoverflow.com/a/65484529/6244201). 

**Question**
* Does failing to decode have serious implications in the app? (since my version still works)

From my understanding, Python3's `decode` is only valid when you have an object of class bytes. Running encode before decode may fix the problem but is it a necessary pair of operations?

Kindly note that I have not built or run this _microblog_ repository but only implemented user login and two-factor authentication in another demo app.

**Comment by miguelgrinberg** [comment]
You are using different versions of packages from those found in the requirements. In particular, you have a newer pyjwt package. Current versions of this package return the token as a string, so there is no need to decode anymore. Just remove the decode call and you'll be fine.

**Comment by GitauHarrison** [comment]
@miguelgrinberg 
Thank you.

The last step to user authentication gives me this error
![push_failure](https://user-images.githubusercontent.com/19605422/112631080-7e6fa400-8e47-11eb-848f-80ae06e96b47.png)

Every step of the way works well except the last part where a user has to click either "Deny" or "Approve". Listening to both events gives me this error from which I can see no logs to identify the exact issue. 

When I look closely, the function `check_push()` in `check_2fa.html` file checks for the status of the user, which in my case defaults to the `else` part. The script for `check_push()` is this:

```
    <script>
        function check_push() {
            $.ajax("{{ url_for('auth.check_2fa_poll') }}").done(function(data) {
                if (data == 'pending') {
                    setTimeout(check_push, 5000);
                }
                else if (data == 'approved') {
                    window.location = "{{ next }}";
                }
                else {
                    window.location = "{{ url_for('auth.login', next=next) }}";
                }
            });
        }

        setTimeout(check_push, 5000);
    </script>
```

What could I be missing?

**Comment by miguelgrinberg** [comment]
This is an error from Authy, not your application. Not sure you have any control over this, maybe it was a temporary issue with the Authy service.

**Comment by GitauHarrison** [comment]
Seems it was. Tried the authentication again and it works.
